/*
 * Copyright 2026 Kintsugi OS Project. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Authors:
 *     Ambuj Varshney, ambuj@kintsugi-os.org
 *
 * This file incorporates work covered by the following copyright and
 * permission notice:
 *
 *   Copyright 2009, Ingo Weinhold, ingo_weinhold@gmx.de.
 *   Copyright 2013-2014, Rene Gollent, rene@gollent.com.
 *   Distributed under the terms of the MIT License.
 */


/**
 * @file DebugInfoEntry.cpp
 * @brief Implementation of the DebugInfoEntry abstract base.
 *
 * Provides default no-op or NULL-returning implementations for every
 * polymorphic accessor and every @c AddAttribute_xxx setter, so that
 * concrete DIE subclasses (defined in DebugInfoEntries.cpp) only need
 * to override the setters relevant to their DWARF tag.  The bulk of
 * the file is generated by the @c DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER
 * macro which expands to a default "not handled" stub.
 */

#include "DebugInfoEntries.h"

#include <new>

#include "AttributeValue.h"
#include "Dwarf.h"


/** @brief Helper macro that defines a default attribute setter returning ATTRIBUTE_NOT_HANDLED. */
#define DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(name)				\
	status_t													\
	DebugInfoEntry::AddAttribute_##name(uint16 attributeName,	\
		const AttributeValue& value)							\
	{															\
		return ATTRIBUTE_NOT_HANDLED;											\
	}


/**
 * @brief Constructs an orphan DIE with no parent.
 */
DebugInfoEntry::DebugInfoEntry()
	:
	fParent(NULL)
{
}


/**
 * @brief Destroys the DIE.  Children are owned and freed elsewhere.
 */
DebugInfoEntry::~DebugInfoEntry()
{
}


/**
 * @brief Hook invoked after parent/child links are set up.
 *
 * @param info Per-CU initialisation context (language info, ...).
 * @retval B_OK Default no-op implementation.
 */
status_t
DebugInfoEntry::InitAfterHierarchy(DebugInfoEntryInitInfo& info)
{
	return B_OK;
}


/**
 * @brief Hook invoked after every attribute has been parsed.
 *
 * @param info Per-CU initialisation context.
 * @retval B_OK Default no-op implementation.
 */
status_t
DebugInfoEntry::InitAfterAttributes(DebugInfoEntryInitInfo& info)
{
	return B_OK;
}


/**
 * @brief Records the parent DIE during tree construction.
 *
 * @param parent Pointer to the parent DIE (may be NULL for unit roots).
 */
void
DebugInfoEntry::SetParent(DebugInfoEntry* parent)
{
	fParent = parent;
}


/**
 * @brief Reports whether this DIE represents a type.
 *
 * @return Default implementation returns @c false; type DIEs override.
 */
bool
DebugInfoEntry::IsType() const
{
	return false;
}


/**
 * @brief Reports whether this DIE introduces a namespace-like scope.
 *
 * @return @c true for namespaces, classes, structs; @c false otherwise.
 */
bool
DebugInfoEntry::IsNamespace() const
{
	return false;
}


/**
 * @brief Returns the DIE's DW_AT_name string, or NULL if unset.
 */
const char*
DebugInfoEntry::Name() const
{
	return NULL;
}

/**
 * @brief Returns the DIE's DW_AT_description string, or NULL if unset.
 */
const char*
DebugInfoEntry::Description() const
{
	return NULL;
}


/**
 * @brief Returns the DW_AT_specification reference, or NULL.
 */
DebugInfoEntry*
DebugInfoEntry::Specification() const
{
	return NULL;
}


/**
 * @brief Returns the DW_AT_abstract_origin reference, or NULL.
 */
DebugInfoEntry*
DebugInfoEntry::AbstractOrigin() const
{
	return NULL;
}


/**
 * @brief Returns the DW_AT_signature type referenced from a TU, or NULL.
 */
DebugInfoEntry*
DebugInfoEntry::SignatureType() const
{
	return NULL;
}


/**
 * @brief Returns a writable pointer to the DIE's location description.
 *
 * @return The DIE's owned LocationDescription, or NULL when DW_AT_location
 *         is not part of this DIE's data model.
 */
LocationDescription*
DebugInfoEntry::GetLocationDescription()
{
	return NULL;
}


/**
 * @brief Reads DW_AT_decl_file via the DIE's declaration-location storage.
 *
 * @param _file Output file index (1-based; resolves against CU file table).
 * @return @c true on success, @c false when no decl-file is available.
 */
bool
DebugInfoEntry::GetDeclarationFile(uint32& _file) const
{
	DeclarationLocation* location = const_cast<DebugInfoEntry*>(this)
		->GetDeclarationLocation();
	if (location == NULL || !location->IsFileSet())
		return false;

	_file = location->file;
	return true;
}


/**
 * @brief Reads DW_AT_decl_line via the DIE's declaration-location storage.
 *
 * @param _line Output 1-based source line number.
 * @return @c true on success.
 */
bool
DebugInfoEntry::GetDeclarationLine(uint32& _line) const
{
	DeclarationLocation* location = const_cast<DebugInfoEntry*>(this)
		->GetDeclarationLocation();
	if (location == NULL || !location->IsLineSet())
		return false;

	_line = location->line;
	return true;
}


/**
 * @brief Reads DW_AT_decl_column via the DIE's declaration-location storage.
 *
 * @param _column Output 1-based source column.
 * @return @c true on success.
 */
bool
DebugInfoEntry::GetDeclarationColumn(uint32& _column) const
{
	DeclarationLocation* location = const_cast<DebugInfoEntry*>(this)
		->GetDeclarationLocation();
	if (location == NULL || !location->IsColumnSet())
		return false;

	_column = location->column;
	return true;
}


/**
 * @brief Default child handler that rejects unexpected children.
 *
 * @param child Newly-parsed child DIE.
 * @retval ENTRY_NOT_HANDLED Always; subclasses override to accept children.
 */
status_t
DebugInfoEntry::AddChild(DebugInfoEntry* child)
{
	// ignore children where we don't expect them
	return ENTRY_NOT_HANDLED;
}


/**
 * @brief Stores DW_AT_decl_file into the DIE's declaration location.
 *
 * @retval B_OK                  Stored successfully.
 * @retval ATTRIBUTE_NOT_HANDLED This DIE has no declaration-location storage.
 */
status_t
DebugInfoEntry::AddAttribute_decl_file(uint16 attributeName,
	const AttributeValue& value)
{
	if (DeclarationLocation* location = GetDeclarationLocation()) {
		location->SetFile(value.constant);
		return B_OK;
	}

	return ATTRIBUTE_NOT_HANDLED;
}


/**
 * @brief Stores DW_AT_decl_line into the DIE's declaration location.
 */
status_t
DebugInfoEntry::AddAttribute_decl_line(uint16 attributeName,
	const AttributeValue& value)
{
	if (DeclarationLocation* location = GetDeclarationLocation()) {
		location->SetLine(value.constant);
		return B_OK;
	}

	return ATTRIBUTE_NOT_HANDLED;
}


/**
 * @brief Stores DW_AT_decl_column into the DIE's declaration location.
 */
status_t
DebugInfoEntry::AddAttribute_decl_column(uint16 attributeName,
	const AttributeValue& value)
{
	if (DeclarationLocation* location = GetDeclarationLocation()) {
		location->SetColumn(value.constant);
		return B_OK;
	}

	return ATTRIBUTE_NOT_HANDLED;
}


/**
 * @brief Stores DW_AT_location into the DIE's location description.
 *
 * Recognises both inline expression blocks and location-list pointers.
 *
 * @retval B_OK                  Stored successfully.
 * @retval B_BAD_DATA            Attribute class was incompatible.
 * @retval ATTRIBUTE_NOT_HANDLED This DIE has no location-description storage.
 */
status_t
DebugInfoEntry::AddAttribute_location(uint16 attributeName,
	const AttributeValue& value)
{
	if (LocationDescription* location = GetLocationDescription()) {
		if (value.attributeClass == ATTRIBUTE_CLASS_LOCLIST) {
			location->SetToLocationList(value.pointer);
			return B_OK;
		}

		if (value.attributeClass == ATTRIBUTE_CLASS_BLOCK) {
			location->SetToExpression(value.block.data, value.block.length);
			return B_OK;
		}
		return B_BAD_DATA;
	}

	return ATTRIBUTE_NOT_HANDLED;
}


/**
 * @brief Accepts (and discards) the DW_AT_sibling attribute.
 *
 * The sibling pointer is a parsing optimisation; this implementation
 * has no need for it because it parses children depth-first directly.
 *
 * @retval B_OK Always.
 */
status_t
DebugInfoEntry::AddAttribute_sibling(uint16 attributeName,
	const AttributeValue& value)
{
	// This attribute is only intended to help the debug info consumer. We don't
	// need it.
	return B_OK;
}


/**
 * @brief Block of default-stub attribute setters.
 *
 * Each macro expansion below produces an @c AddAttribute_xxx member
 * function whose default implementation returns
 * @c ATTRIBUTE_NOT_HANDLED.  Concrete DIE subclasses override only the
 * subset of setters they want to consume.
 */
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(name)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(ordering)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(byte_size)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(bit_offset)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(bit_size)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(stmt_list)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(low_pc)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(high_pc)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(language)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(discr)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(discr_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(visibility)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(import)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(string_length)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(common_reference)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(comp_dir)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(const_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(containing_type)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(default_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(inline)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(is_optional)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(lower_bound)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(producer)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(prototyped)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(return_addr)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(start_scope)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(bit_stride)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(upper_bound)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(abstract_origin)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(accessibility)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(address_class)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(artificial)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(base_types)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(calling_convention)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(count)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(data_member_location)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(declaration)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(discr_list)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(encoding)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(external)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(frame_base)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(friend)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(identifier_case)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(macro_info)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(namelist_item)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(priority)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(segment)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(specification)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(static_link)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(type)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(use_location)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(variable_parameter)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(virtuality)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(vtable_elem_location)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(allocated)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(associated)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(data_location)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(byte_stride)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(entry_pc)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(use_UTF8)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(extension)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(ranges)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(trampoline)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_column)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_file)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_line)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(description)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(binary_scale)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(decimal_scale)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(small)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(decimal_sign)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(digit_count)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(picture_string)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(mutable)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(threads_scaled)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(explicit)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(object_pointer)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(endianity)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(elemental)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(pure)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(recursive)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(signature)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(main_subprogram)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(data_bit_offset)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(const_expr)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(enum_class)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(linkage_name)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(string_length_bit_size)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(string_length_byte_size)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(rank)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(str_offsets_base)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(addr_base)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(rnglists_base)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(dwo_name)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(reference)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(rvalue_reference)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(macros)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_all_calls)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_all_source_calls)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_all_tail_calls)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_return_pc)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_origin)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_parameter)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_pc)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_tail_call)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_target)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_target_clobbered)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_data_location)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_data_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(noreturn)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(alignment)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(export_symbols)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(deleted)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(defaulted)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(loclists_base)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_site_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_site_data_value)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_site_target)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(call_site_target_clobbered)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(tail_call)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(all_tail_call_sites)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(all_call_sites)
DEFINE_DEBUG_INFO_ENTRY_ATTR_SETTER(all_source_call_sites)


/**
 * @brief Returns a writable pointer to the DIE's declaration-location storage.
 *
 * @return Default returns NULL; DIEs that carry decl-file/line/column override.
 */
DeclarationLocation*
DebugInfoEntry::GetDeclarationLocation()
{
	return NULL;
}


/**
 * @brief Stores a parsed AttributeValue into a DynamicAttributeValue field.
 *
 * Maps each supported attribute class (constant, reference, block) onto
 * the matching DynamicAttributeValue setter.
 *
 * @param toSet  Output field to populate.
 * @param value  Parsed attribute value.
 * @retval B_OK        Stored successfully.
 * @retval B_BAD_DATA  Attribute class was not one of the supported three.
 */
status_t
DebugInfoEntry::SetDynamicAttributeValue(DynamicAttributeValue& toSet,
	const AttributeValue& value)
{
	switch (value.attributeClass) {
		case ATTRIBUTE_CLASS_CONSTANT:
			toSet.SetTo(value.constant);
			return B_OK;
		case ATTRIBUTE_CLASS_REFERENCE:
			toSet.SetTo(value.reference);
			return B_OK;
		case ATTRIBUTE_CLASS_BLOCK:
			toSet.SetTo(value.block.data, value.block.length);
			return B_OK;
		default:
			return B_BAD_DATA;
	}
}


/**
 * @brief Stores a parsed AttributeValue into a ConstantAttributeValue field.
 *
 * Mirrors @ref SetDynamicAttributeValue but accepts strings instead of
 * DIE references.
 *
 * @param toSet  Output field to populate.
 * @param value  Parsed attribute value.
 * @retval B_OK        Stored successfully.
 * @retval B_BAD_DATA  Attribute class was not constant/string/block.
 */
status_t
DebugInfoEntry::SetConstantAttributeValue(ConstantAttributeValue& toSet,
	const AttributeValue& value)
{
	switch (value.attributeClass) {
		case ATTRIBUTE_CLASS_CONSTANT:
			toSet.SetTo(value.constant);
			return B_OK;
		case ATTRIBUTE_CLASS_STRING:
			toSet.SetTo(value.string);
			return B_OK;
		case ATTRIBUTE_CLASS_BLOCK:
			toSet.SetTo(value.block.data, value.block.length);
			return B_OK;
		default:
			return B_BAD_DATA;
	}
}


/**
 * @brief Stores a parsed AttributeValue into a MemberLocation field.
 *
 * Constants become byte offsets, blocks become DWARF expressions, and
 * pointer values become location-list references.
 *
 * @param toSet  Output field to populate.
 * @param value  Parsed attribute value.
 * @retval B_OK        Stored successfully.
 * @retval B_BAD_DATA  Attribute class was not constant/block/loclist.
 */
status_t
DebugInfoEntry::SetMemberLocation(MemberLocation& toSet,
	const AttributeValue& value)
{
	switch (value.attributeClass) {
		case ATTRIBUTE_CLASS_CONSTANT:
			toSet.SetToConstant(value.constant);
			return B_OK;
		case ATTRIBUTE_CLASS_BLOCK:
			toSet.SetToExpression(value.block.data, value.block.length);
			return B_OK;
		case ATTRIBUTE_CLASS_LOCLIST:
			toSet.SetToLocationList(value.pointer);
			return B_OK;
		default:
			return B_BAD_DATA;
	}
}
